#Query: Find all of Maggie’s grandmothers. Result variable name: ?grandmother.


PREFIX rdf:     <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX foaf:  <http://xmlns.com/foaf/0.1/>
PREFIX  sim:     <http://www.ifi.uio.no/IN3060/simpsons#>
PREFIX fam:     <http://www.ifi.uio.no/IN3060/family#>
PREFIX xsd:     <http://www.w3.org/2001/XMLSchema#>

SELECT ?grandmother
WHERE {
    { 
        sim:Maggie fam:hasFather ?father . 
        ?father fam:hasMother ?grandmother . 
    }
    UNION
    { 
        sim:Maggie fam:hasMother ?mother . 
        ?mother fam:hasMother ?grandmother . 
    }
    UNION
    { 
        sim:Maggie fam:hasParent ?parent . 
        ?parent fam:hasMother ?grandmother . 
    }
}
