#Query: Find everyone with a name with ‘M’ as first letter. Result variable name: ?person.


PREFIX rdf:     <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX foaf:  <http://xmlns.com/foaf/0.1/>
PREFIX  sim:     <http://www.ifi.uio.no/IN3060/simpsons#>
PREFIX fam:     <http://www.ifi.uio.no/IN3060/family#>
PREFIX xsd:     <http://www.w3.org/2001/XMLSchema#>
SELECT ?person
WHERE {
    ?person foaf:name ?name .
    FILTER(regex(str(?name), "^M.+", "i"))
}
