# Write a CONSTRUCT SPARQL query that produces a FOAF file for Homer, adding his name, a foaf:knows relationship to his spouse, and the name of his spouse.


PREFIX rdf:     <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX foaf:  <http://xmlns.com/foaf/0.1/>
PREFIX  sim:     <http://www.ifi.uio.no/IN3060/simpsons#>
PREFIX fam:     <http://www.ifi.uio.no/IN3060/family#>
PREFIX xsd:     <http://www.w3.org/2001/XMLSchema#>

CONSTRUCT {
    sim:Homer a foaf:Person .
    sim:Homer foaf:name ?name .
    sim:Homer foaf:knows ?spouse .
    
    ?spouse a foaf:Person .
    ?spouse foaf:name ?spousename
}
WHERE {
    sim:Homer fam:hasSpouse ?spouse .
    sim:Homer foaf:name ?name .
    ?spouse foaf:name ?spousename
}